---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: description
  label: description
- name: sections
  type: blocks
  label: sections
  template_types:
  - title-slide
  - media-slide
  config:
    min: 
    max: 
pages:
- src/routes/work/posts/markdown-test.md
- src/routes/work/posts/sample-project.md
